export const offlineCopy = {
  savedLocally: "Salvo neste aparelho",
  online: "Online",
  syncing: "Sincronizando",
  synced: "Sincronizado",
  failed: "Falha ao sincronizar",
  pendingTitle: "Coletas pendentes de sincronizar",
  pendingEmpty: "Nenhuma coleta pendente neste aparelho.",
  retry: "Tentar de novo",
  resume: "Continuar",
  discard: "Descartar rascunho",
  discardConfirm: "Descartar este rascunho salvo neste aparelho? A guia oficial não é apagada.",
  quotaExceeded: "Não há espaço neste aparelho para guardar o rascunho.",
  searchOffline: "A busca de cliente precisa de internet. Cadastre um novo cliente para continuar.",
  authExpired: "Entre de novo para sincronizar as coletas deste aparelho.",
  queuedFinalize: "Coleta salva neste aparelho. O número oficial será gerado ao sincronizar.",
  stepCliente: "Cliente",
  stepItens: "Itens",
  stepRevisao: "Revisão",
  stepAssinatura: "Assinatura",
} as const;
